# This file contains values from Cookiecutter

default_context:
  project_name: "channel-automation"
  project_description: "channel-automation is tool to atomate telegram channels"
  organization: "g1ibby"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "g1ibby"
  email: "hello@g1ibby.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
