"""Add ChannelInfo bottom text

Revision ID: 094bb455727b
Revises: 2d86531468e2
Create Date: 2023-06-02 11:25:35.170668

"""
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094bb455727b'
down_revision = '2d86531468e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channelinfo', sa.Column('bottom_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channelinfo', 'bottom_text')
    # ### end Alembic commands ###
