"""Remove name field from Source model

Revision ID: 2e2a52129a5d
Revises: 
Create Date: 2023-04-16 09:02:19.766598

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2e2a52129a5d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "source",
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
