- hosts: all
  become: yes
  tasks:
    - name: Update the system
      apt:
        update_cache: yes
        upgrade: dist

    - name: Ensure APT uses the HTTPS transport
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Get the latest version of Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Ensure project directory exists
      file:
        path: /opt/channel_automation
        state: directory

    - name: Stop Docker Compose Services
      shell: docker-compose down
      args:
        chdir: /opt/channel_automation
      ignore_errors: yes

    - name: Clear project directory
      shell: rm -rf /opt/channel_automation/*

    - name: Extract the Repository Tarball
      unarchive:
        src: /tmp/repo.tar.gz
        dest: /opt/channel_automation
        remote_src: yes

    - name: Login to GitHub Container Registry
      docker_login:
        registry: ghcr.io
        username: g1ibby
        password: "{{ github_token }}"

    - name: Create .env file with environment variables
      copy:
        dest: /opt/channel_automation/.env
        content: |
          image_name="ghcr.io/g1ibby/channel-automation:latest"
          APP_TELEGRAM_BOT_TOKEN="{{ telegram_bot_token }}"
          APP_ADMIN_CHAT_ID="{{ admin_chat_id }}"
          APP_ASSISTANT_TOKEN="{{ assistant_token }}"

    - name: Pull the latest Docker images
      shell: docker-compose pull
      args:
        chdir: /opt/channel_automation

    - name: Run Docker Compose Up
      shell: docker-compose up -d
      args:
        chdir: /opt/channel_automation
